server:
  port: 8002
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8443/eureka/
      
spring:
  application:
    name: offer-service
  datasource:
    url: jdbc:mysql://localhost:3306/mysales
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0